name: CI/CD Workflow

on:
  workflow_dispatch:

jobs:  
  build:
    name: Build And Test
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      ## Checkout the repository ###
      - name: Checkout Main Repository
        uses: actions/checkout@v4

      ## Prepare OS and Java environment
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'microsoft'
          cache: gradle

      ## Make Gradle Executable
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Cache Gradle and wrapper
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      ## Build the project and generate APK with Gradle
      - name: Build & Generate app APK
        run: |
          ./gradlew assembleDebug --stacktrace

      - name: Instrumented Tests
        uses: ReactiveCircus/android-emulator-runner@v2
        with:
          api-level: 30
          target: google_apis
          arch: x86_64
          script: ./gradlew connectedCheck
