name: CI/CD Workflow

on:
  workflow_dispatch:

jobs:  
  build:
    name: Build And Test
    runs-on: ubuntu-latest
    timeout-minutes: 20

    steps:
      ## Checkout the repository ###
      - name: Checkout Main Repository
        uses: actions/checkout@v4

      ## Prepare OS and Java environment
      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'microsoft'
          cache: gradle

      ## Make Gradle Executable
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      ## Build the project and generate APK with Gradle
      - name: Build & Generate app APK
        run: |
          ./gradlew assembleDebug --stacktrace
